const PRODUCT = [
    {
        id: 1,
        name: "PREDATOR FREAK.4 FLEXIBLE GROUND BOOTS",
        category: "football-boots",
        price: "6299.00",
        salePrice: "3150.00",
        thumbnail: "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/a58aaeeee8a04a3e951fad0a00a1a8af_9366/Predator_Freak.4_Flexible_Ground_Boots_Red_FY6319_01_standard.jpg",
        image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/5019fbd256aa4347a4f2ad0a00a1c6f5_9366/Predator_Freak.4_Flexible_Ground_Boots_Red_FY6319.jpg",
        subname: "VERSATILE BOOTS FOR CONTROLLING THE PITCH.",
        desc: "Every time you cross that white line, you enter a whole new world. An alternative reality where you call the shots. The pitch is yours to control. Set your inner freak free in adidas Predator. The soft textile upper on these football boots is textured to enhance your close control. It sits on a versatile outsole made to master firm ground, hard ground and artificial grass.",
        specification: ["Regular fit", "Flexible ground outsole", "Lace closure", "Coated textile upper", "Product code: FY6319"],
        importer: "adidas India Marketing Private Limited, Office no. 6, 2nd Floor, Sector-B, Pocket no. 7, Plot no. 11, Vasant Kunj, New Delhi - 110070",
        quantity: "2 N",
        gender: "Men",
        country: "Cambodia",
        ratings: "3.3",
        numOfReviews: "3",
        reviews: []
    },
    // {
    //     id: 2,
    //     name: "X GHOSTED.4 FLEXIBLE GROUND BOOTS",
    //     category: "football-boots",
    //     price: "4999.00",
    //     salePrice: "2500.00",
    //     thumbnail: "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/0e2ea22d7527400db913ac39011557c8_9366/X_Ghosted.4_Flexible_Ground_Boots_Yellow_FW6953_01_standard.jpg",
    //     image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/6d26fef6bd5f4c4e90d7ac39011602fc_9366/X_Ghosted.4_Flexible_Ground_Boots_Yellow_FW6953.jpg",
    //     subname: "VERSATILE BOOTS PRIMED FOR SPEED.",
    //     desc: "The only thing that makes defenders sweat more than seeing you on the pitch? Not seeing you at all. Pull on X Ghosted and discover next-level speed. These adidas football boots keep you quick with a lightweight upper. They have a flexible ground outsole, so you sprint hard on firm ground, hard ground and artificial grass.",
    //     specification: ["Regular fit", "Flexible ground outsole", "Lace closure", "Coated textile upper", "Low-cut collar", "Product code: FY6319"],
    //     importer: "adidas India Marketing Private Limited, Office no. 6, 2nd Floor, Sector-B, Pocket no. 7, Plot no. 11, Vasant Kunj, New Delhi - 110070",
    //     quantity: "2 N",
    //     gender: "Men",
    //     country: "Cambodia",
    //     ratings: "4.3",
    //     numOfReviews: "3",
    //     reviews: []
    // },
    {
        id: 3,
        name: "RUNNING ADI CLASSIC SNEAKERS",
        category: "running-shoes",
        price: "2499.00",
        salePrice: "1499.00",
        thumbnail: "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/55695aced4f3471581ffadb90136589a_9366/Running_Adi_Classic_Sneakers_Black_EY2909_01_standard.jpg",
        image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/eb56db5cea0d4d5ca457adb90136571f_9366/Running_Adi_Classic_Sneakers_Black_EY2909.jpg",
        subname: "ICONIC 3 STRIPES SHOES FOR EVERY MOVE.",
        desc: "Rise to the occasion and make it one to remember. Classic adidas sneakers boast the iconic 3-Stripes for vintage feels that perfectly balance every look between classy and casual. Made to match every vibe these kicks give you the confidence of knowing you hit the mark every single time. High tops, low tops, lifted looks, low-to-the-ground styles, canvas uppers and leather builds give you all the space to work with your style. And a variety of color in each kick flairs your personality while their black and white bases exude your composure. Keeping poise beyond looks, these classic sports-rooted shoes are made with soft feels — some even with Cloudfoam technology — so your day can go uninterrupted. A variety of sizing options allow you to match with anyone — from your best friend to your significant other, and even your mini-me. Timeless for a reason, classic adidas shoes are the only shoes that truly meet every occasion.",
        specification: ["Regular fit", "EVA outsole", "Lace closure", "Comfort Outsole", "Mesh upper", "Sole: Ethylene Vinyl Acetate", "Product code: FY6319"],
        importer: "adidas India Marketing Private Limited, Office no. 6, 2nd Floor, Sector-B, Pocket no. 7, Plot no. 11, Vasant Kunj, New Delhi - 110070",
        quantity: "2 N",
        gender: "Men",
        country: "India",
        ratings: "4.2",
        numOfReviews: "14",
        reviews: []
    },
    {
        id: 4,
        name: "SOLARBOOST 3 TOKYO SHOES",
        category: "running-shoes",
        price: "15999.00",
        salePrice: "9599.00",
        thumbnail: "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/41a7ec8be45d4b5fb9e6ad200060ca2a_9366/Solarboost_3_Tokyo_Shoes_White_S42994_01_standard.jpg",
        image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/aee4cb09cd974aeeb6bead200060e4d7_9366/Solarboost_3_Tokyo_Shoes_White_S42994.jpg",
        subname: "ROAD RUNNING SHOES BUILT FOR TRAINING OR RACE DAY.",
        desc: "Whether you\"re training for your first half marathon or running your fifth 26.2, these adidas running shoes provide comfort and support mile after mile.Responsive Boost cushioning, LEP and a Continental™ Stretchweb outsole work together to provide a smooth, energised ride. This product is made with Primegreen, a series of high- performance recycled materials. 50 % of the upper is recycled content.No virgin polyester.",
        specification: ["Regular fit", "Midsole drop: 10 mm (heel: 32 mm / forefoot: 22 mm); Arch type: Normal", "Lace closure", "Textile lining", "Textile upper", "Sole: Ethylene Vinyl Acetate", "Boost midsole", "Stretchweb outsole with Continental™ Rubber", "Product code: FY6319"],
        importer: "adidas India Marketing Private Limited, Office no. 6, 2nd Floor, Sector-B, Pocket no. 7, Plot no. 11, Vasant Kunj, New Delhi - 110070",
        quantity: "2 N",
        gender: "Men",
        country: "China",
        ratings: "5.0",
        numOfReviews: "1",
        reviews: []
    },
    {
        id: 5,
        name: "ADIDAS SPORTSWEAR HOODED TRACK SUIT",
        category: "tracksuit",
        price: "7599.00",
        salePrice: "5319.00",
        thumbnail: "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/18e532eebf83445f9c5aad0b00879110_9366/adidas_Sportswear_Hooded_Track_Suit_Black_H15580_21_model.jpg",
        image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/e2b15a4b188d4e1e8694ad0b00879f88_9366/adidas_Sportswear_Hooded_Track_Suit_Black_H15580.jpg",
        subname: "A SLEEK, SPORTY TRACK SUIT WITH ADIDAS DNA SHOWCASED LOUD AND CLEAR.",
        desc: "There\"s no disputing the icon status of the track suit.There\"s only wearing it. If you didn\"t understand before, you understand now with this adidas track suit.What else lets you go from home to gym to work to out to home without missing a beat? In fact you\"re not missing anything here. Comfort is covered. Style is covered. You\"re good.This product is made with Primegreen, a series of high- performance recycled materials.",
        specification: ["Regular fit", "Elastic cuffs on jacket and pants", "Full zip with drawcord-adjustable hood", "Plain weave", "100% recycled polyester plain weave", "Front pockets on jacket and pants", "Elastic waist with drawcord", "Product code: H15580"],
        importer: "adidas India Marketing Private Limited, Office no. 6, 2nd Floor, Sector-B, Pocket no. 7, Plot no. 11, Vasant Kunj, New Delhi - 110070",
        quantity: "1 N",
        gender: "Men",
        country: "Combodia",
        ratings: "4.7",
        numOfReviews: "3",
        reviews: []
    },
]

export default PRODUCT