import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import JoinBanner from '../../../components/Home/JoinBanner';
import ProductCard from '../../../components/Card/ProductCard';
import PRODUCT from '../../../components/List/Product.list';

const ProductList = ({ products }) => {

    const router = useRouter()

    const [productState, setProductState] = useState(products);
    const [sort, setSort] = useState('newest')


    return (
        <div className="min-h-screen w-full">
            <Head>
                <title>addidas Official Website India</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <main className="flex flex-col justify-center items-center mt-10">
                <div className="w-10/12 mt-6 px-4 lg:px-10">

                    <div className="flex mb-6">
                        <span className="uppercase underline text-black mr-4 font-bold cursor-pointer" onClick={() => router.back()}>BACK</span>
                    </div>

                    <h1 className="uppercase font-medium text-4xl italic tracking-tighter">{router.query.category ? router.query.category : "All-products"} <span className='text-xs text-gray-400'>[ 0 ]</span></h1>
                    <p className='lg:w-1/2 text-sm my-2 mb-4'>The adidas range of mens shoes has got you covered, if you are striving to be the best or you just want the best fit for your daily life. With iconic designs and high-performance technologies, you can be sure that your shoes wont let you down.</p>
                    <hr />

                    <div className='flex flex-wrap justify-between w-full'>
                        <div className='flex mx-3'>
                            <h1 className='uppercase font-bold w-fit flex items-center'>
                                Sort By: &nbsp;
                            </h1>
                            <select name='sort' className='hover:border-black border border-white cursor-pointer p-3 outline-none' value={sort} onChange={(e) => setSort(e.target.value)}>
                                <option value="newest">Newest</option>
                                <option value="top">Top Sellers</option>
                                <option value="pricelh">Prices [Low - High]</option>
                                <option value="pricehl">Prices [High - Low]</option>
                            </select>
                        </div>
                    </div>

                    <hr className='mb-4' />

                    <div className="grid grid-cols-4 mt-2 mb-8 justify-center">
                        {
                            PRODUCT.map((e) => <ProductCard data={e} key={e._id} />)
                        }
                    </div>

                    <div className='my-16 mt-40'>
                        <h1 className='text-3xl font-medium mb-2'>MENS SHOES</h1>
                        <p>A pair of adidas shoes, for casual or sporting activities, is a must have for men of all ages. A great way to finish off your outfit with style and look the part, no matter the occasion, is to choose your shoes wisely, and adidas is here to help with our range of shoes for men.</p>

                        <h1 className='text-xl font-medium mb-2 mt-6'>SPORTING ESSENTIALS TO HELP YOU TRAIN LIKE A PRO</h1>
                        <p>Choose your mens shoes with care, taking into consideration the return you want to see from your activity, whether for a day on the golf course, a training session for the next football season, a running plan for a marathon, or hiking in the mountains. The adidas range of shoes for men is designed using state-of-the-art technology and innovative features that will suit your exercise style. Football boots exist to play on soft ground with agility stud configuration, or hard ground with lightweight, firm ground outsoles. Up your game with a pair of football boots that hug your feet with a lightweight mesh upper. Golfers can choose shoes with a Primeknit upper that molds itself to your foot or a pair with a leather upper that keeps your feet warm and dry on cold, wet golf days. Challenge your personal best with a pair of adidas running shoes for men made with advanced Boost technology in the midsole that gives you extra lift with every step. Hikers, pick up a pair of lightweight GORE-TEX® shoes to keep your feet dry on rainy days.</p>
                    </div>
                </div>

                <JoinBanner />
            </main>
        </div>
    )
}

export default ProductList


// export async function getServerSideProps({ query }) {

//     let products = null;

//     if (Object.keys(query).length === 0) {
//         try {
//             const res = await getProducts();
//             if (res.data.success) {
//                 products = res.data.products
//             } else {
//                 products = []
//             }
//         } catch (err) {
//             console.log(err.message)
//         }
//     } else {
//         try {
//             const res = await getFilteredProducts(query);
//             if (res.data.success) {
//                 products = res.data.product
//             } else {
//                 products = []
//             }
//         } catch (err) {
//             console.log(err.message)
//         }
//     }



//     return {
//         props: { products }, // will be passed to the page component as props
//     }
// }